# This file was generated by GoReleaser. DO NOT EDIT.
cask "tshx" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "63b1d3e01e26ef89a87278453fba5ae507a4b35b96900eef86e7da55d5a89143"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed7c100688c49c92347cf51b6e872a658d8731d1aef5aa24d4b35a51450d1f66"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5464cb99cc28129b4a608c4125cc05ce32511391ac0a652d0964e44bc2f0b4bb"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6cff046cd10d36b39063a05da915635c7c5b8019393e8a2adf99f8e73fa65ff7"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tshx"
  desc "kubectx-style context switcher for Teleport (tsh)"
  homepage "https://github.com/vtrenton/tshx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tshx"

  # No zap stanza required
end
