# This file was generated by GoReleaser. DO NOT EDIT.
cask "tshx" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "2e2a1c94e44b0c3d100f410191b90a9f975a59e36c2e1e7f73a09f88d11fbc73"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c179a5825a496558321eb50f616dc4086eae8a4d6e59f89851b77970b9a034a6"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9894a9fccea8ec2f63219ed89137a3af1dbc17be1d88d1d5e949ee76d107af31"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc7d68ccdbf7462819fdd5b4f1cce6b53116b94ad2ae8708c5ab113245f9bf2e"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tshx"
  desc "kubectx-style context switcher for Teleport (tsh)"
  homepage "https://github.com/vtrenton/tshx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tshx"

  # No zap stanza required
end
