# This file was generated by GoReleaser. DO NOT EDIT.
cask "tshx" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "663371a8ab8dc49cfc5b80371a6378093db6cdb49cd245ac59f2d2545f8d1988"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "073ae3beb77aa62512437a6a4ab912ec799b46fadd8c81f74cbd2a7cddb6b69d"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0a535d9232344658720ac25c58ea944f8d1340ca9d3434289c47d10b6b8930b6"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc24893a3d2ff337c0b8e0152a37c4cc5a48335e1cfbefb140d774e23327c180"
      url "https://github.com/vtrenton/tshx/releases/download/v#{version}/tshx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tshx"
  desc "kubectx-style context switcher for Teleport (tsh)"
  homepage "https://github.com/vtrenton/tshx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tshx"

  # No zap stanza required
end
